### ISSUE TITLE
Hybrid: help menu search results

### ISSUE THREAD

**Issue by CharlesButcher** [SpiraMira/HybridMode-Public#13]
I don't think this has been reported specifically: visual glitches in the help menu when you type something into the search box. (macOS 10.14.2, Hybrid Mode v1.4).

![screenshot 2018-12-12 at 10 06 21](https://user-images.githubusercontent.com/8853681/49862357-ed9b6880-fdf5-11e8-88b0-8e8d25465d0e.png)

**Comment by SpiraMira** [comment]
Thanks for reporting.

- Is that Finder Help in Light Mode? If not, what App?

**Comment by CharlesButcher** [comment]
It's the same with any app (the screenshot is from Safari). Yes, it's light mode.

The screenshot below shows what it looks like before I type anything in the search box. I'm not sure if that's exactly what you see, but it looks perfectly normal to me. Once I start typing, however, I get those grey background boxes.

![screenshot 2018-12-12 at 15 17 12](https://user-images.githubusercontent.com/8853681/49879047-05d4ad00-fe21-11e8-9223-9c81f0a7c870.png)

**Comment by CharlesButcher** [comment]
Dark mode is similar:

![screenshot 2018-12-12 at 15 22 03](https://user-images.githubusercontent.com/8853681/49879374-be9aec00-fe21-11e8-8011-00d24206e720.png)

This is a Mac mini 2011 (5,1).

**Comment by CharlesButcher** [comment]
Sorry Patrice. These OK?

![screenshot 2018-12-12 at 15 29 46](https://user-images.githubusercontent.com/8853681/49879980-0e2de780-fe23-11e8-8378-872fd5776247.png)
![screenshot 2018-12-12 at 15 29 38](https://user-images.githubusercontent.com/8853681/49879982-0e2de780-fe23-11e8-9951-90888c0b44c3.png)

**Comment by SpiraMira** [comment]
Thanks.  
A v1.4.1 is in the works with a fix for the SpotLight Selections.  I'll look into this menubar fix also.

**Comment by ptkovsky** [comment]
Looks like fixed now. Thanks!

**Comment by maciboy** [comment]
![bildschirmfoto 2018-12-14 um 13 10 37](https://user-images.githubusercontent.com/19333006/50002808-a8b43500-ffa1-11e8-8f0b-9a8bda4abf03.png)

Can’t confirm :(
Screenshot made with Safari… (Hybrid 1.4.1 as provided in other thread)

**Comment by SpiraMira** [comment]
Is this only Safari help?  
My help in Finder and other core apps look fine.  
I didn't specifically address this in v1.4.1.

**Comment by maciboy** [comment]
- Finder
- Safari
- Mail
…

MacBook Pro 6,2, Intel HD Graphics

**Comment by ptkovsky** [comment]
![test](https://user-images.githubusercontent.com/10148835/50018055-bc2dc300-ffd6-11e8-9fbb-9c28e486de29.png)

**Comment by SpiraMira** [comment]
Yes, I think 1.4.1 fixed this.  I will close this issue as fixed in 1.4.1.

**Comment by maciboy** [comment]
Strange... since as I tested, it is not fixed :(

**Comment by CharlesButcher** [comment]
Agreed. Some good progress, obviously, and I'm grateful. But not fixed for maciboy and me.

**Comment by julianfairfax** [comment]
It's still an issue for me too. With the latest version that I actually got running on 10.14.3.
